"""new analytics tables

Revision ID: 8e34acdfe057
Revises: 898b51d238e0
Create Date: 2026-01-04 04:39:15.614093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e34acdfe057'
down_revision: Union[str, None] = '898b51d238e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatsession_id'), 'chatsession', ['id'], unique=False)
    op.create_index(op.f('ix_chatsession_ip_address'), 'chatsession', ['ip_address'], unique=False)
    op.create_index(op.f('ix_chatsession_session_uuid'), 'chatsession', ['session_uuid'], unique=True)
    op.create_table('analyticsevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyticsevent_event_type'), 'analyticsevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_analyticsevent_id'), 'analyticsevent', ['id'], unique=False)
    op.create_table('chatfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_chatfeedback_id'), 'chatfeedback', ['id'], unique=False)
    op.add_column('lead', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead', 'chatsession', ['session_id'], ['id'])
    op.add_column('message', sa.Column('session_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('role', sa.String(), nullable=False))
    op.add_column('message', sa.Column('content', sa.String(), nullable=False))
    op.add_column('message', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'chatsession', ['session_id'], ['id'])
    op.drop_column('message', 'ip_address')
    op.drop_column('message', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'response_time_ms')
    op.drop_column('message', 'tokens_used')
    op.drop_column('message', 'content')
    op.drop_column('message', 'role')
    op.drop_column('message', 'session_id')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    op.drop_column('lead', 'session_id')
    op.drop_index(op.f('ix_chatfeedback_id'), table_name='chatfeedback')
    op.drop_table('chatfeedback')
    op.drop_index(op.f('ix_analyticsevent_id'), table_name='analyticsevent')
    op.drop_index(op.f('ix_analyticsevent_event_type'), table_name='analyticsevent')
    op.drop_table('analyticsevent')
    op.drop_index(op.f('ix_chatsession_session_uuid'), table_name='chatsession')
    op.drop_index(op.f('ix_chatsession_ip_address'), table_name='chatsession')
    op.drop_index(op.f('ix_chatsession_id'), table_name='chatsession')
    op.drop_table('chatsession')
    # ### end Alembic commands ###
