"""Add Lead table

Revision ID: c5784994ef8e
Revises: 7fe59fd5e2e1
Create Date: 2026-01-04 01:48:36.965975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5784994ef8e'
down_revision: Union[str, None] = '7fe59fd5e2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=True)
    op.create_index(op.f('ix_lead_id'), 'lead', ['id'], unique=False)
    op.create_index(op.f('ix_lead_name'), 'lead', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_name'), table_name='lead')
    op.drop_index(op.f('ix_lead_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
